[#ftl]
[@pp.dropOutputFile /]
[@pp.changeOutputFile name="tasks.c" /]
/*
 * This file has been generated by the SPC5Studio NIL RTOS Kernel Component.
 *
 * Do not edit this file manually, any change will be lost after next
 * code generation, edit the component configuration instead.
 */

#include "components.h"
#include "tasks.h"

[#assign scode = conf.instance.tasks_configuration.shared_code.value[0]?trim /]
[#if scode != ""]
/*
 * Tasks shared code generated from configuration.
 */
${conf.instance.tasks_configuration.shared_code.value[0]?trim}

[/#if]
/*
 * Tasks table generated from configuration.
 */
THD_TABLE_BEGIN
[#list conf.instance.tasks_configuration.tasks.task_settings as settings]
  [#assign name = settings.readable_name.value[0]?trim /]
  [#assign sname = settings.symbolic_name.value[0]?trim /]
  [#assign arg = settings.argument.value[0]?trim /]
  THD_TABLE_ENTRY(${sname}_wa, "${name}", ${sname}, ${arg})
[/#list]
THD_TABLE_END
