[#ftl]
[@pp.dropOutputFile /]
[@pp.changeOutputFile name="tasks.h" /]
/*
 * This file has been generated by the SPC5Studio HSM RTOS Kernel Component.
 *
 * Do not edit this file manually, any change will be lost after next
 * code generation, edit the component configuration instead.
 */

#ifndef _TASKS_H_
#define _TASKS_H_

[#list conf.instance.tasks_configuration.tasks.task_settings as settings]
  [#assign sname = settings.symbolic_name.value[0]?trim /]
  [#assign stksize = settings.stack_size.value[0]?trim /]
extern THD_WORKING_AREA(${sname + "_wa"}, ${stksize});
[/#list]

#ifdef __cplusplus
extern "C" {
#endif
[#list conf.instance.tasks_configuration.tasks.task_settings as settings]
  [#assign sname = settings.symbolic_name.value[0]?trim /]
  THD_FUNCTION(${sname}, arg);
[/#list]
#ifdef __cplusplus
}
#endif

#endif /* _TASKS_H_ */
