[#ftl]
[@pp.dropOutputFile /]
[#--
  -- Iterating through all the defined ISRs, a different file is generated
  -- for each one.
  --]
[#list conf.instance.isrs_configuration.isrs.isr_settings as settings]
  [#assign identifier = settings.identifier.value[0]?trim /]
  [#assign vnum = settings.number.value[0]?trim /]
  [#assign name = settings.name_override.value[0]?trim /]
  [#if name == ""]
    [#assign name = "vector" + vnum /]
  [/#if]
  [@pp.changeOutputFile name="isr_" + identifier?lower_case + ".c" /]
/*
 * This file has been generated by the NIL RTOS Kernel Port Component.
 *
 * Do not edit this file manually, any change will be lost after next
 * code generation, edit the component configuration instead.
 */

#include "components.h"

#define ISR_NAME            ${name}

${settings.isr_code.value[0]}
[/#list]
