[#ftl]
[#--
  -- Iterating through all the defined ISRs, a different file is generated
  -- for each one.
  --]
[#list conf.instance.isrs_configuration.isrs.isr_settings as settings]
  [#assign identifier = settings.identifier.value[0]?trim /]
  [@pp.dropOutputFile /]
  [@pp.changeOutputFile name="isr_" + identifier?lower_case + ".c" /]
/*
 * This file has been generated by the SPC5Studio NIL RTOS Kernel Port Component.
 *
 * Do not edit this file manually, any change will be lost after next
 * code generation, edit the component configuration instead.
 */

#include "components.h"

${settings.isr_code.value[0]}
[/#list]
