[#ftl]
[@pp.dropOutputFile /]
[@pp.changeOutputFile name="isrs.h" /]
/*
 * This file has been generated by the NIL RTOS Kernel Port Component.
 *
 * Do not edit this file manually, any change will be lost after next
 * code generation, edit the component configuration instead.
 */
[#if conf.instance.isrs_configuration.isrs.isr_settings?size > 0]

/*
 * Vector numbers definitions.
 */
  [#list conf.instance.isrs_configuration.isrs.isr_settings as settings]
    [#assign id = settings.identifier.value[0]?trim /]
    [#assign number = settings.number.value[0]?trim /]
    [#assign name = ("IRQ_VECTOR_" + id)?right_pad(35) /]
#define ${name} ${number}
  [/#list]
[/#if]
